
$terminal = alacritty
$fileManager = $terminal -t 'file manager' -e lf
$menu1 = wofi --show drun
$menu2 = dmenu_run_history
$browser = brave-browser
$brave-proxy = brave-browser \
  --user-data-dir=~/.config/brave-proxy
  --proxy-server="socks5://127.0.0.1:1080" \
  --host-resolver-rules="MAP * ~NOTFOUND , EXCLUDE 127.0.0.1" \
  --disable-quic
