#!/bin/bash

SOURCE=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

mkdir -p ~/.local
mkdir -p ~/.config

DIRS=(
	~/.config/emacs
	~/.config/terminal
	~/.config/qtile
	~/.config/systemd
	~/.local/share/fonts
	~/.config/alacritty
	~/.config/go
	~/.config/sxhkd
	~/.config/conky
	~/.config/hypr
	~/.config/waybar
	~/.local/emacs
	~/.local/scripts
	~/.local/wallpaper
)

FILES=(
	~/.bashrc
	~/.xinitrc
)


for DIR in ${DIRS[@]};do
	rm -rf $DIR
done

for FILE in ${FILES[@]};do
	rm -f $FILE
done


ln -sf $SOURCE/../emacs				~/.config/emacs
ln -sf $SOURCE/../terminal			~/.config/terminal
ln -sf $SOURCE/../.bashrc			~/.bashrc
ln -sf $SOURCE/../.xinitrc			~/.xinitrc
ln -sf $SOURCE/../qtile				~/.config/qtile
ln -sf $SOURCE/../systemd			~/.config/systemd
ln -sf $SOURCE/../fonts         	~/.local/share/fonts
ln -sf $SOURCE/../alacritty			~/.config/alacritty
ln -sf $SOURCE/../go 				~/.config/go
ln -sf $SOURCE/../sxhkd				~/.config/sxhkd
ln -sf $SOURCE/../conky				~/.config/conky
ln -sf $SOURCE/../hypr				~/.config/hypr
ln -sf $SOURCE/../waybar				~/.config/waybar
ln -sf $SOURCE/../emacs-profiles	~/.local/emacs
ln -sf $SOURCE						~/.local/scripts
ln -sf $SOURCE/../wallpaper			~/.local/wallpaper

