#!/bin/bash

SOURCE=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )



rm -r ~/.config/emacs
rm -r ~/.config/terminal
rm -r ~/.bashrc
rm -r ~/.xinitrc
rm -r ~/.config/qtile
rm -r ~/.config/systemd
rm -r ~/.local/share/fonts
rm -r ~/.config/alacritty
rm -r ~/.config/go
rm -r ~/.config/sxhkd
rm -r ~/.config/conky


ln -sf $SOURCE/../emacs		~/.config/emacs
ln -sf $SOURCE/../terminal	~/.config/terminal
ln -sf $SOURCE/../.bashrc	~/.bashrc
ln -sf $SOURCE/../.xinitrc	~/.xinitrc
ln -sf $SOURCE/../qtile		~/.config/qtile
ln -sf $SOURCE/../systemd	~/.config/systemd
ln -sf $SOURCE/../fonts         ~/.local/share/fonts
ln -sf $SOURCE/../alacritty	~/.config/alacritty
ln -sf $SOURCE/../go 		~/.config/go
ln -sf $SOURCE/../sxhkd		~/.config/sxhkd
ln -sf $SOURCE/../conky		~/.config/conky
# ln -sf $SOURCE		~/.local/bin
